data_split:
  test_size: 0.33
  random_state: 42

model_initialization:
  max_depth: 4
  random_state: 0
  n_jobs: -1

model_cross_validation:
  cv: 3
  n_jobs: -1
  verbose: 1
  scoring: "r2"
  param_grid:
    max_depth: [4, 5]
    min_samples_leaf: [50, 75]
    n_estimators: [100, 150]


