# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  REGION: us-central1
  JOB_NAME: justeat_regressor_training
  PROJECT_ID: citric-program-331111

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # - name: Test with pytest
      #   run: |
      #     pytest

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_VERTEX_AI_JUSTEAT }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_VERTEX_AI_JUSTEAT }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          gcloud builds submit --config cloudbuild.yaml .

      - name: Run training job on Vertex AI
        run: |
          gcloud ai custom-jobs create \
            --region=${{env.REGION}} \
            --display-name=${{env.JOB_NAME}} \
            --config=vertex_run.yaml

      - name: Save model to Certex model registry
        # run: |
        #   gcloud ai models upload \
        #     --region=${{env.REGION}} \
        #     --display-name=justeat-regressor \
        #     --container-image-uri=gcr.io/${{env.PROJECT_ID}}/justeat-pipeline
        #     --artifact-uri=gs://cloud-ai-platform-4de6a256-deb4-4f4f-8b9f-8595e0183ea1/models/
        run: |
          python src/gcp/vertex_model_upload.py

      - name: Deploy model to endpoint
        run: python src/gcp/vertex_model_deploy.py
